name: black

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Installing
      run: |
        sudo apt update -y
        sudo apt -y install python3-pip python3-setuptools python3-wheel
        pip3 install black isort

    - name: Version
      run: |
        python3 --version
        $HOME/.local/bin/black --version
        $HOME/.local/bin/isort --version

    - name: Run black and isort
      run: |
        $HOME/.local/bin/black . $(grep '^#!.*/bin/.*python.*$' . -Ir|cut -d: -f1)
        $HOME/.local/bin/isort . $(grep '^#!.*/bin/.*python.*$' . -Ir|cut -d: -f1)

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Apply black and isort changes

[skip ci]"
